In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

In [44]:
# Load dataset
df = pd.read_csv("Titanic_train.csv")

# First 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [45]:
# select and prepare
df_model = df[["Survived","Pclass","Sex","Age","Fare"]]

df_model["Sex"]= df_model["Sex"].map({"male":0,"female":1})

C:\Users\Aakas\AppData\Local\Temp\ipykernel_4008\1156686671.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model["Sex"]= df_model["Sex"].map({"male":0,"female":1})

In [47]:
df_model.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    0  22.0   7.2500
1         1       1    1  38.0  71.2833
2         1       3    1  26.0   7.9250
3         1       1    1  35.0  53.1000
4         0       3    0  35.0   8.0500

In [48]:
df_model.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [49]:
X = df_model.drop("Survived",axis=1)
y= df_model["Survived"]

In [50]:
X.head()

   Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

In [51]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [52]:
imputer =SimpleImputer(strategy="mean")
X_imputed =imputer.fit_transform(X)

X_imputed[:10]

array([[ 3.        ,  0.        , 22.        ,  7.25      ],
       [ 1.        ,  1.        , 38.        , 71.2833    ],
       [ 3.        ,  1.        , 26.        ,  7.925     ],
       [ 1.        ,  1.        , 35.        , 53.1       ],
       [ 3.        ,  0.        , 35.        ,  8.05      ],
       [ 3.        ,  0.        , 29.69911765,  8.4583    ],
       [ 1.        ,  0.        , 54.        , 51.8625    ],
       [ 3.        ,  0.        ,  2.        , 21.075     ],
       [ 3.        ,  1.        , 27.        , 11.1333    ],
       [ 2.        ,  1.        , 14.        , 30.0708    ]])

In [53]:
import numpy as np
np.isnan(X_imputed).any()

np.False_

In [54]:
X_train,X_test,y_train,y_test = train_test_split(X_imputed,y,test_size=0.2,random_state=42)

In [55]:
nb_model = GaussianNB()

nb_model.fit(X_train,y_train)

GaussianNB()

In [56]:
y_pred = nb_model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n", classification_report(y_test,y_pred))

Accuracy: 0.7597765363128491
Confusion Matrix:
 [[83 22]
 [21 53]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.79      0.79       105
           1       0.71      0.72      0.71        74

    accuracy                           0.76       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.76      0.76      0.76       179

In [ ]:
# Sumary

#out of 177  total pridictions  around 75% were corect.
#that's desent  accuracy ,especially for simple probailistic model like Naive Bayes.

# fairly balanced performance across both classes
#some room for improvement,especially in distinguishing class 1